### ISSUE TITLE
(No action needed) message application suite: wrong exit code

### ISSUE THREAD

**Issue by raulk** [filecoin-project/chain-validation#249]
This test does not test what it claims to test:

https://github.com/filecoin-project/chain-validation/blob/a084d8d9919e4b752e4340380fa240c2ebdab524/suites/message/message_application.go#L50-L55

The gas limit of 1 makes it trigger the `SysErrOutOfGas` exit code, but the intention of the scenario is to test an unknown sender. When gas is not the limiting factor, this throws `SysErrSenderInvalid`.

---

No need to act here, we're fixing it during our migration to VM Conformance Test Vectors, but I thought I'd report it.

**Comment by anorth** [comment]
I think this test is doing what it says. It is resolving an ambiguity: when both the sender doesn't exist and the gas limit is too low, fail because of the gas limit. The comment might be improved to "fail due to lack of gas _even_ when sender is unknown". 

There might be a different question about whether we want that behaviour, but in either case a test like this should encode it.

**Comment by raulk** [comment]
@anorth Yeah, it's semantics.
